---
name: Build

on:
  push: {}

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: corepack enable && yarn set version 3.5.0 && yarn

      - name: Run CI
        run: yarn ci
